owner: jae1911
repo: status.rexo.network
assignees: jae1911
user-agent: jae1911

sites:
  - name: Main Website
    url: https://rexo.network
  - name: e-mails
    url: $EMAILURI
  - name: ns1
    check: "tcp-ping"
    url: ns1.rexo.network
    port: 53
  - name: awa
    check: "tcp-ping"
    url: awa.rexo.network
    port: 53

status-website:
  cname: status.rexo.network
  logoUrl: https://bm.jae.fi/Logo-abs.svg
  name: Rexonet Status
  introTitle: "Rexonet status"
  theme: night
  introMessage: Status of Rexonet.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
